create error return

diff --git a/metroae b/metroae
--- a/metroae
+++ b/metroae
@@ -925,15 +925,17 @@ function setup_container {
 
     if [[ $config_template_status -ne 0 || $config_docs_status -ne 0 || $deploy_keys_status -ne 0 || $deploy_status -ne 0 || $common_status -ne 0 ]]; then
         echo ""
-        write_to_screen_and_script_log "We had a problem copying one or more files to the data directory."
-        echo "The MetroAE container is running, but you may not have the latest files on disk. Try running 'metroae container setup' again."
+        write_to_screen_and_script_log "Setup of the MetroAE container is complete. However, we had a problem copying one or more files to the data directory."
+        echo "The MetroAE container is running. You can use it, but you may not have the latest files on disk."
+        echo "You can try running 'metroae container setup' again to correct this problem."
         echo ""
+        exit 1
+    else
+        echo ""
+        write_to_screen_and_script_log "Setup of the MetroAE container is complete. Execute 'metroae container status' for status."
+        echo ""
+        return 0
     fi
-
-    echo ""
-    write_to_screen_and_script_log "MetroAE container setup complete. Execute 'metroae container status' for status."
-    echo ""
-    return 0
 }
 
 function update_container_files {
