update wording

diff --git a/docker/metroae b/docker/metroae
--- a/docker/metroae
+++ b/docker/metroae
@@ -26,7 +26,7 @@ checkDocker() {
 
 	if [ $? -ne 0 ]
 	then
-		echo "MetroAE container requires Docker.  Please install at https://docs.docker.com"
+		echo "MetroÆ container requires Docker.  See https://docs.docker.com for details"
 		exit 1
 	fi
 }
@@ -34,15 +34,15 @@ checkDocker() {
 getHostOperatingSystem() {
 	echo "checking os type" >> ./metroae.log
 	stat /etc/os-release >> ./metroae.log 2>> ./metroae.log
-    
-    if [ $? -ne 0 ] 
+
+    if [ $? -ne 0 ]
     then
 		osRelease=$NON_LINUX
-	fi 
-		
+	fi
+
 }
 
-getMaxContainerVersion() { 
+getMaxContainerVersion() {
     versions=`docker images | grep $metroAEImage | awk '{ print $2}'`
 	maxContainerVersion=''
 	for version in $versions
@@ -57,96 +57,96 @@ getMaxContainerVersion() {
                 maxContainerVersion=$version
         fi
 	done
-	
+
 	if [ -z $maxContainerVersion ]
 	then
 		maxContainerVersion='1.0'
 	fi
-	
+
 	echo "Max Container version detected $maxContainerVersion" >> ./metroae.log
-	
+
 }
 
-getContainerID() { 
+getContainerID() {
 	getMaxContainerVersion
 	containerID=`docker ps -a | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $1}'`
 }
 
 getRunningContainerID() {
-	getMaxContainerVersion 
+	getMaxContainerVersion
 	runningContainerID=`docker ps | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $1}'`
 }
 
-getImageID() { 
-	getMaxContainerVersion 
+getImageID() {
+	getMaxContainerVersion
 	imageID=`docker images | grep $metroAEImage | grep $maxContainerVersion | awk '{ print $3}'`
 }
 
 
 stop() {
 	getRunningContainerID
-	
+
 	if [ -z $runningContainerID  ]
 	then
 		echo "No Container to stop"
 		return 0
 	fi
-	
-	docker stop $runningContainerID 
+
+	docker stop $runningContainerID
 	status=$?
 	if [ $status -ne 0 ]
 	then
-		echo "Stopping metroae docker container failed"
-	else 
-		echo "Container successfully stopped" 
+		echo "Stopping container failed"
+	else
+		echo "Container successfully stopped"
 	fi
-	
+
 	return $status
 }
 
-run() { 
+run() {
 	getImageID
-	
-	if [ -z $imageID ] 
+
+	if [ -z $imageID ]
 	then
 		setup
 		status=$?
 		if [ $status -ne 0 ]
 		then
-			echo "Unable to setup metroae container"
-			return $status 
+			echo "Unable to setup MetroÆ container"
+			return $status
 		fi
-	else 
+	else
 		getContainerID
-		
+
 		if [ -z $containerID ]
 		then
 			while read -r line; do declare $line; done < ~/.metroae
 			networkArgs=""
-			getHostOperatingSystem 
+			getHostOperatingSystem
 			if [ $osRelease  -eq $LINUX ]
 			then
 				networkArgs=" --network host"
 			else
 				networkArgs=" -p $UI_PORT:5001"
 			fi
-			
+
 			userName=`whoami`
 			groupName=`id -g -n`
-			
-			docker run -e USER_NAME=$userName -e GROUP_NAME=$groupName -d $networkArgs -v $METROAE_MOUNT_POINT:/data:Z -v $IMAGES_MOUNT_POINT:/images:Z --name metroae $metroAEImage:$maxContainerVersion 
-		else 
+
+			docker run -e USER_NAME=$userName -e GROUP_NAME=$groupName -d $networkArgs -v $METROAE_MOUNT_POINT:/data:Z -v $IMAGES_MOUNT_POINT:/images:Z --name metroae $metroAEImage:$maxContainerVersion
+		else
 			docker start $containerID
 		fi
-	    
+
 	    status=$?
-		if [ $status -ne 0 ] 
+		if [ $status -ne 0 ]
 		then
-			echo "Unable to run the latest metroae docker image"
-		else 
-			echo "Succesfully started the metroae container"
+			echo "Unable to run the latest MetroÆ container"
+		else
+			echo "Succesfully started the MetroÆ container"
 		fi
-		
+
 		return $status
 	fi
 }
@@ -155,20 +155,20 @@ deleteContainerID() {
 	getContainerID
 	if [ -z $containerID ]
 	then
-		echo "No container to remove" 
+		echo "No container to remove"
 		return 0
 	fi
-	
+
 	echo "Removing container with id $containerID" >> ./metroae.log
 	docker rm $containerID 2>> ./metroae.log
-	
+
 	if [ $? -ne 0 ]
 	then
-		echo "Remove of metroae container failed" 
+		echo "Remove of MetroÆ container failed"
 		return 1
 	fi
-	
-	echo "MetroAE container removed successfully"
+
+	echo "MetroÆ container removed successfully"
 }
 
 destroy() {
@@ -176,51 +176,51 @@ destroy() {
 	if [ -z $1 ]
 	then
 		confirmation="init"
-	else 
+	else
 		confirmation=$1
 	fi
-	
+
 	while [[ $confirmation != "yes" ]] && [[ $confirmation  != "no" ]] && [[ $confirmation  != "y" ]] && [[ $confirmation != "n" ]]
 	do
 		read -p "Do you really want to destroy the container (yes/no): " confirmation
 	done
- 
-	
+
+
 	if [[ $confirmation != "yes" ]] && [[ $confirmation != "y" ]]
 	then
-		echo "Destroy Cancelled by user"
+		echo "Destroy canceled by user"
 		return 1
 	fi
-	
+
 	stop
 	if [ $? -ne 0 ]
 	then
 		return 1
 	fi
-	
-	deleteContainerID 
+
+	deleteContainerID
 	if [ $? -ne 0 ]
 	then
 		return 1
 	fi
-	
+
 	getImageID
 	if [ -z $imageID ]
 	then
 		echo "No Image to remove"
 		return 0
 	fi
-	
+
 	echo "Destroying MetroAE container..." | tee  -a ./metroae.log
-	
+
 	docker rmi $imageID  2>> ./metroae.log
-	
+
 	if [ $? -ne 0 ]
 	then
-		echo "Remove of metroae image failed" 
+		echo "Remove of MetroÆ image failed"
 		return 1
 	fi
-	
+
 	return 0
 }
 
@@ -239,53 +239,53 @@ getFromS3()
     -H "Content-Type: $content_type" \
     -H "Authorization: AWS ${S3KEY}:$signature" \
     "https://$bucket.s3.amazonaws.com$aws_path$file" > $temp$file | tee -a ./metroae.log 2>> ./metroae.log
-   
+
 }
 
 copySSHId() {
 	if [ -z $1 ]
 	then
-		echo "please provide the user and host to copy the key to. e.g. caso@localhost\n"
+		echo "Please provide the user and host to copy the key to. e.g. caso@localhost\n"
 		exit 1
-	fi 
+	fi
 	runContainerIfNotRunning
-	
+
 	docker exec -it $runningContainerID ssh-copy-id -i /source/id_rsa.pub $1
 }
 
-pull() { 
+pull() {
 	if [ ! -z $1 ]
 	then
 		maxContainerVersion=$1
 	fi
-	
+
 	ping -c 5 $registryHost >> ./metroae.log 2>> ./metroae.log
-	
+
 	if [ $? -ne 0 ]
 	then
 		echo "Could not ping the local registry to download container" | tee -a ./metroae.log
-		echo "Retrieving the container from amazon s3" | tee -a ./metroae.log
+		echo "Retrieving the container from Amazon s3" | tee -a ./metroae.log
 		getFromS3
-		
+
 		if [ $? -ne 0 ]
 		then
-			echo "unable to pull metroae container exiting" | tee -a ./metroae.log
+			echo "Unable to pull MetroÆ container exiting" | tee -a ./metroae.log
 			exit 1
 		fi
-		
+
 		docker load -i $temp$file
-	else 
-		echo "Retrieving MetroAE container..." | tee -a ./metroae.log
+	else
+		echo "Retrieving MetroÆ container..." | tee -a ./metroae.log
 		docker pull $metroAEImage:$maxContainerVersion 2>> ./metroae.log
 	fi
-	
+
 	status=$?
-	if [ $status -ne 0 ] 
+	if [ $status -ne 0 ]
 	then
-		echo "Unable to pull the $maxContainerVersion metroae docker image"
+		echo "Unable to pull the $maxContainerVersion MetroÆ image"
 	fi
-	
-	return $status	
+
+	return $status
 }
 
 getUserPathInput() {
@@ -296,141 +296,141 @@ getUserPathInput() {
 		read -p "$1" path
 		echo "checking path for $1" >> ./metroae.log
 		stat $path >> ./metroae.log 2>> ./metroae.log
-		
+
 		validPath=$?
-		if [ $validPath -ne 0 ] 
+		if [ $validPath -ne 0 ]
 		then
 			echo "Invalid path provided"
 		fi
-		
+
 		# check to see if the path ends with passed in directory
 		if [[ "$path" != *"$2" ]]
 		then
 			path=$path/$2
 			mkdir -p $path
 		fi
-		
+
 	done
 }
 
 setup() {
-	echo "Setup MetroAE container..."
-	
+	echo "Setup MetroÆ container..."
+
 	getContainerID
 	getRunningContainerID
-	
+
 	if [ ! -z $containerID ] || [ ! -z $runningContainerID ]
 	then
-		echo "You already have the MetroAE container setup. Running setup will destroy the"
+		echo "You already have the MetroÆ container setup. Running setup will destroy the"
 		echo "existing container and create a new one. Your data on disk will be preserved."
 		echo "If you continue, create the new container, and use the same data and image"
 		echo "mount points, no changes are required. If you change the mount points, however"
 		echo "you will need to copy your existing data to the new mount points."
-		
+
 		confirmation="init"
 		while [[ $confirmation != "yes" ]] && [[ $confirmation  != "no" ]] && [[ $confirmation  != "y" ]] && [[ $confirmation != "n" ]]
 		do
 			read -p "Do you want to continue with setup (yes/no): " confirmation
 		done
-	 
-		
+
+
 		if [[ $confirmation != "yes" ]] && [[ $confirmation != "y" ]]
 		then
-			echo "Setup Cancelled by user"
+			echo "Setup canceled by user"
 			return 1
 		fi
 	fi
-	
-	getImageID 
-	
+
+	getImageID
+
 	if [ -z $imageID ]
-	then 
+	then
 		pull
 	fi
-	
-	if [ $? -ne 0 ] 
+
+	if [ $? -ne 0 ]
 	then
 		return 1
 	fi
-	
+
 	if [ -z $1 ]
 	then
-		getUserPathInput "Specify the full path to store data on the host system, metroae_data directory will be created after the provided path. If the path ends with metroae_data we are going to use the path as is: " metroae_data
+		getUserPathInput "Specify the full path to the directory where your user data will be stored on the host system. Setup will create a subdirectory, metroae_data, in the directory you specify. If the path you specify ends with metroae_data, we will use that subdirectory and not create one. Data directory path: " metroae_data
 		data_path=$path
-	else 
+	else
 		data_path=$1
 	fi
-	
+
 	if [ -z $2 ]
 	then
-		getUserPathInput "Specify the full path of image files on the host system, metroae_images directory will be created after the provided path. If the path ends with metroae_images we are going to use the path as is: " metroae_images
+		getUserPathInput "Specify the full path to the directory where your Nuage Networks image files will be stored on the host system. Setup will create a subdirectory, metroae_images, in the directory you specify. If the path you specify ends with metroae_images, we will use that subdirectory and not create one. Image directory path: " metroae_images
 		images_path=$path
-	else 
+	else
 		images_path=$2
 	fi
-	
-	getHostOperatingSystem 
+
+	getHostOperatingSystem
 	if [ $osRelease -eq $NON_LINUX ]
 	then
 		if [ -z $3 ]
 		then
 			read -p "Specify the REST API/UI access port for the container: " port
-		else 
+		else
 			port=$3
 		fi
 		echo UI_PORT=$port >> ~/.metroae
 	fi
-	
+
 	echo IMAGES_MOUNT_POINT=$images_path >> ~/.metroae
 	echo METROAE_MOUNT_POINT=$data_path >> ~/.metroae
-	
-	
+
+
 	#stop and remove existing container if any
-	getRunningContainerID 
+	getRunningContainerID
 	if [ ! -z $runningContainerID ]
 	then
 		stop
-	fi 
-	
+	fi
+
 	getContainerID
-	if [ ! -z $containerID ] 
+	if [ ! -z $containerID ]
 	then
 		deleteContainerID
 	fi
-	
-	
+
+
 	#Ask if TLS needs to be setup
 	confirmation="init"
-	
+
 	while [[ $confirmation != "yes" ]] && [[ $confirmation  != "no" ]] && [[ $confirmation  != "y" ]] && [[ $confirmation != "n" ]]
 	do
 		read -p "Do you want to set a certificate and start the UI (yes/no): " confirmation
 	done
-	
+
 	if [[ $confirmation == "yes" ]] && [[ $confirmation == "y" ]]
 	then
 		loadCertificates
 		return 0
 	fi
-	
+
 	run
 	return $?
 }
 
-upgradeDocker() { 
-	destroy 
+upgradeDocker() {
+	destroy
 	if [ $? -ne 0 ]
 	then
 		return 1
 	fi
-	
+
 	pull
-	run	
+	run
 }
 
-runContainerIfNotRunning() { 
+runContainerIfNotRunning() {
 	getRunningContainerID
-	
+
 	if [ -z $runningContainerID ]
 	then
 		run
@@ -438,9 +438,9 @@ runContainerIfNotRunning() {
 	fi
 }
 
-dockerExec() { 
-	runContainerIfNotRunning 
-	
+dockerExec() {
+	runContainerIfNotRunning
+
 	environment='-e ANSIBLE_FORCE_COLOR=true'
 	for env in `env`
 	do
@@ -450,16 +450,16 @@ dockerExec() {
 			if [[ "$env" =~ ^$filter ]]
 			then
 				filtered=1
-				
+
 			fi
 		done
-		
+
 		if [ $filtered -eq 0 ]
 		then
 			environment="$environment -e $env"
 		fi
 	done
-	
+
 	docker exec $environment $runningContainerID "$@"
 }
 
@@ -467,13 +467,13 @@ dockerMetroAEExec() {
 	dockerExec /source/nuage-metro/metroae "$@"
 }
 
-stopUI() { 
-	runContainerIfNotRunning 
+stopUI() {
+	runContainerIfNotRunning
 	docker exec $runningContainerID /source/UI.sh stop
 }
 
-startUI() { 
-	runContainerIfNotRunning 
+startUI() {
+	runContainerIfNotRunning
 	docker exec -it $runningContainerID /source/UI.sh start
 }
 
@@ -490,19 +490,19 @@ loadCertificates() {
 	else
 		certificate=$1
 	fi
-	
+
 	keyfile=''
 	if [ -z $2 ]
 	then
 		read -p "Enter the path to key file: " keyfile
-	else 
+	else
 		keyfile=$2
 	fi
-	 
+
 	docker exec -it $runningContainerID /source/UI.sh loadCertificates $1 $2
 }
 
-interactive() { 
+interactive() {
 	runContainerIfNotRunning
 	docker exec -it $runningContainerID /bin/bash
 
@@ -511,7 +511,7 @@ interactive() {
 unzip-files() {
 	if [ $# -gt 1 ]
 	then
-		dockerExec /source/nuage-metro/nuage-unzip.sh "$@"  
+		dockerExec /source/nuage-metro/nuage-unzip.sh "$@"
 	else
 		dockerExec /source/nuage-metro/nuage-unzip.sh "$@" /images/
 	fi
@@ -527,13 +527,13 @@ genExampleFromSchema() {
 
 status() {
 	docker ps -a
-	echo "Currently used docker settings..." 
+	echo "Currently settings..."
 	while read -r line; do declare $line; done < ~/.metroae
 	echo "images_mount: $IMAGES_MOUNT_POINT"
 	echo "metroae_mount: $METROAE_MOUNT_POINT"
-	
+
 	getHostOperatingSystem
-	
+
 	if [ $osRelease -eq $LINUX ]
 	then
 		echo "ui_port: 5001"
@@ -551,29 +551,30 @@ disableEncryption() {
 	docker exec $runningContainerID /source/UI.sh disableEncryption
 }
 
-help() { 
-	echo "Nuage Networks MetorAE docker container management script"
+help() {
+	echo "Nuage Networks Metro Automation Engine (Æ) Container CLI"
 	echo "Usage:"
 	echo ""
 	echo "	./metroae [actions] | <workflow> [deployment] [options]"
 	echo "	[actions]:	supported actions are help, pull, setup, start, stop, status, destroy, upgrade-engine, stop-ui, start-ui, status-ui, unzip-files, convert-build-vars-to-deployments, generate-example-from-schema, encrypt-credentials, enable-ui-encryption, disable-ui-encryption, copy-ssh-id "
-	echo "additionally supports commands that can be executed in the docker container" 
-	
-	getRunningContainerID 
-	
+	echo "See MetroÆ documentation for details on the actions listed here."
+	echo "If no [action] is specified, the <workflow>, [deployment], and [options] will be passed into the container for execution by MetroÆ."
+
+	getRunningContainerID
+
 	if [ -z $runningContainerID ] && [ $1 == 0 ]
 	then
 		exit
 	fi
-	
+
 }
 
 # check docker
-checkDocker 
+checkDocker
 
 # main functionality
 
-if [ $# -eq 0 ] 
+if [ $# -eq 0 ]
 then
 	help 0
 	exit 0
@@ -594,7 +595,7 @@ do
 		shift
 		;;
 		pull)
-		if [ -z $2 ] 
+		if [ -z $2 ]
 		then
 			pull
 		else
@@ -611,7 +612,7 @@ do
 		if [ -z $2 ]
 		then
 			setup
-		else 
+		else
 			setup $2
 			shift
 		fi
@@ -625,14 +626,14 @@ do
 		if [ -z $2 ]
 		then
 			destroy
-		else 
+		else
 			destroy $2
 			shift
 		fi
 		shift
 		;;
 		upgrade-engine)
-		upgradeDocker 
+		upgradeDocker
 		shift
 		;;
 		stop-ui)
