Updating the script to support automated testing

diff --git a/docker/metroae b/docker/metroae
--- a/docker/metroae
+++ b/docker/metroae
@@ -34,13 +34,13 @@ checkDocker() {
 
 getHostOperatingSystem() {
 	echo "checking os type" >> ./metroae.log
+	set +e
 	stat /etc/os-release >> ./metroae.log 2>> ./metroae.log
-
-    if [ $? -ne 0 ]
+	if [ $? -ne 0 ]
     then
 		osRelease=$NON_LINUX
 	fi
-
+	set -e
 }
 
 getMaxContainerVersion() {
@@ -147,9 +147,11 @@ run() {
 		else
 			echo "Succesfully started the MetroÆ container"
 		fi
-
+	
 		return $status
 	fi
+	
+	return 0
 }
 
 deleteContainerID() {
@@ -259,10 +261,12 @@ pull() {
 	then
 		maxContainerVersion=$1
 	fi
+	
+	repo="Docker registry"
 
 	ping -c 5 $registryHost >> ./metroae.log 2>> ./metroae.log
 
-	if [ $? -ne 0 ]
+	if [[ $? -ne 0 || ( ! -z $1 && "$1" = "S3" ) ]] 
 	then
 		echo "Could not ping the local registry to download container" | tee -a ./metroae.log
 		echo "Retrieving the container from Amazon S3" | tee -a ./metroae.log
@@ -275,15 +279,18 @@ pull() {
 		fi
 
 		docker load -i $temp$file
+		repo="Amazon S3"
 	else
 		echo "Retrieving MetroÆ container..." | tee -a ./metroae.log
-		docker pull $metroAEImage:$maxContainerVersion 2>> ./metroae.log
+		docker pull $metroAEImage:$maxContainerVersion | tee -a ./metroae.log
 	fi
 
 	status=$?
 	if [ $status -ne 0 ]
 	then
-		echo "Unable to pull the $maxContainerVersion MetroÆ image"
+		echo "Unable to pull the $maxContainerVersion MetroÆ image" | tee -a ./metroae.log
+	else 
+		echo "Successfully Pulled the container from $repo" | tee -a ./metroae.log
 	fi
 
 	return $status
@@ -359,6 +366,7 @@ setup() {
 		getUserPathInput "Specify the full path to the directory where your user data will be stored on the host system. Setup will create a subdirectory, called metroae_data, in the directory you specify. If the path you specify ends with metroae_data, we will use that subdirectory and not create one. Data directory path: " metroae_data
 		data_path=$path
 	else
+		echo "setting data path to passed in parameter $1" | tee -a ./metroae.log
 		data_path=$1
 	fi
 
@@ -367,6 +375,7 @@ setup() {
 		getUserPathInput "Specify the full path to the directory where your Nuage Networks image files will be stored on the host system. Setup will create a subdirectory, called metroae_images, in the directory you specify. If the path you specify ends with metroae_images, we will use that subdirectory and not create one. Image directory path: " metroae_images
 		images_path=$path
 	else
+		echo "setting image path to passed in parameter $2" | tee -a ./metroae.log
 		images_path=$2
 	fi
 
@@ -377,6 +386,7 @@ setup() {
 		then
 			read -p "Specify the REST API/UI access port for the container: " port
 		else
+			echo "setting UI port to passed in parameter $3" | tee -a ./metroae.log
 			port=$3
 		fi
 		echo UI_PORT=$port >> ~/.metroae
@@ -384,7 +394,6 @@ setup() {
 
 	echo IMAGES_MOUNT_POINT=$images_path >> ~/.metroae
 	echo METROAE_MOUNT_POINT=$data_path >> ~/.metroae
-
 
 	#stop and remove existing container if any
 	getRunningContainerID
@@ -399,9 +408,13 @@ setup() {
 		deleteContainerID
 	fi
 
-
 	#Ask if TLS needs to be setup
-	confirmation="init"
+	if [ ! -z $4 ] 
+	then
+		confirmation=$4
+	else
+		confirmation="init"
+	fi
 
 	while [[ $confirmation != "yes" ]] && [[ $confirmation  != "no" ]] && [[ $confirmation  != "y" ]] && [[ $confirmation != "n" ]]
 	do
@@ -475,7 +488,7 @@ stopUI() {
 
 startUI() {
 	runContainerIfNotRunning
-	docker exec -it $runningContainerID /source/UI.sh start
+	docker exec -it $runningContainerID /source/UI.sh start $1
 }
 
 UIstatus() {
@@ -499,6 +512,8 @@ loadCertificates() {
 	else
 		keyfile=$2
 	fi
+	
+	getRunningContainerID
 
 	docker exec -it $runningContainerID /source/UI.sh loadCertificates $1 $2
 }
@@ -547,7 +562,8 @@ status() {
 }
 
 vaultPassword() {
-	dockerExec /usr/bin/python /source/nuage-metro/encrypt_credentials.py
+	runContainerIfNotRunning
+	docker exec -it $runningContainerID /usr/bin/python /source/nuage-metro/encrypt_credentials.py
 }
 
 disableEncryption() {
@@ -581,8 +597,8 @@ help() {
 	echo ""
 
 	getRunningContainerID
-
-	if [ -z $runningContainerID ] && [ $1 == 0 ]
+	
+	if [ -z $runningContainerID ]
 	then
 		exit
 	fi
@@ -596,7 +612,7 @@ checkDocker
 
 if [ $# -eq 0 ]
 then
-	help 0
+	help
 	exit 0
 fi
 
@@ -610,8 +626,9 @@ do
 	key=$1
 	case $key in
 		@(help|--h|-h|--help|-help))
-		help ${#ArrayName[@]}
+		help
 		POSITIONAL+=("$1")
+		exec=true
 		shift
 		;;
 		pull)
@@ -629,14 +646,18 @@ do
 		shift
 		;;
 		setup)
-		if [ -z $2 ]
+		if [ $# -gt 0 ]
 		then
-			setup
-		else
-			setup $2
 			shift
+			setup "$@"
+			shift
+			shift
+			shift
+			shift
+		else
+			setup
+			shift 
 		fi
-		shift
 		;;
 		stop)
 		stop
@@ -661,7 +682,13 @@ do
 		shift
 		;;
 		start-ui)
-		startUI
+		if [ -z $2 ]
+		then
+			startUI
+		else
+			startUI $2
+			shift
+		fi
 		shift
 		;;
 		status-ui)
